# Generated by Django 3.0.6 on 2020-05-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('show_in_menu', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('articles', 'Articles'), ('polls', 'Polls'), ('products', 'Products')], default='draft', max_length=10)),
            ],
        ),
    ]
