# Generated by Django 3.0.6 on 2020-05-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_article_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='gallery/FitSimplify.jpg', upload_to='gallery'),
        ),
    ]
