# Generated by Django 3.0.6 on 2020-06-03 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_polls.answer_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.TextField(default=None)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(default='PROVIDE QUESTION', max_length=200)),
                ('question_desc', models.TextField()),
                ('whyweask', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.Answer')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('polls.answer',),
        ),
        migrations.CreateModel(
            name='MC',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.Answer')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('polls.answer',),
        ),
        migrations.CreateModel(
            name='ShortAnswer',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.Answer')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('polls.answer',),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StringInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.TextField(default=None)),
                ('stored_text', models.TextField()),
                ('short_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.ShortAnswer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.TextField(default=None)),
                ('int_input', models.IntegerField(default=0)),
                ('short_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.ShortAnswer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FloatInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.TextField(default=None)),
                ('float_input', models.FloatField(default=0.0)),
                ('short_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.ShortAnswer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.TextField(default=None)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Card')),
                ('mc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.MC')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
