# Generated by Django 3.0.6 on 2020-05-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.URLField(default='https://www.google.com/'),
        ),
    ]
